# setup_certbot.yml
---
  - hosts: servers
    gather_facts: no
    become: true    
    tasks: 
      - name: install certbot (snap)
        shell: 
          cmd: snap install --classic certbot

      - name: symlink certbot
        file:
          src: /snap/bin/certbot
          dest: /usr/bin/certbot
          state: link
      
      - name: certbot --apache ()
        shell: 
          cmd: certbot --apache -n -m user@domain.com -d domain