# setup_certbot.yml
---
  - hosts: servers
    gather_facts: no
    become: true    
    tasks: 
      - 
      - name: snap install --classic certbot
        shell: 
          cmd: snap install --classic certbot
      
      - name: ln -s /snap/bin/certbot /usr/bin/certbot
        shell: 
          cmd: ln -s /snap/bin/certbot /usr/bin/certbot
 
      - name: certbot --apache
        shell: 
          cmd: certbot --apache