# setup_iptables.yml
  - hosts: servers
    gather_facts: no
    become: true    
    tasks: 
    - name: allow ssh
      firewalld:
        service: ssh
        permanent: true
        state: enabled
        immediate: yes

    - name: allow https
      firewalld:
        service: https
        permanent: true
        state: enabled
        immediate: yes

    - name: allow http
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: allow control ip
      firewalld:
        source: 192.168.122.1/32
        permanent: true
        state: enabled
        immediate: yes

#    - name: allow control ip (2)
#      firewalld:
#        source: 192.168.123.1/32
#        permanent: true
#        state: disabled
#        immediate: yes

